/* tslint:disable */
/* eslint-disable */
/**
 * Spire
 * Spire API documentation
 *
 * The version of the OpenAPI document: 3.0
 * Contact: akkadius1@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

const params = new Proxy(new URLSearchParams(window.location.search), {
    get: (searchParams, prop: string) => searchParams.get(prop),
  }) as any;
if (params.remote_backend) {
localStorage.setItem('remote-backend', params.remote_backend);
}
  
const remote_backend = params.remote_backend ?? localStorage.getItem('remote-backend');

export * from "./api";
export * from "./configuration";
export * from "./models";
